#James Page
#this file contains dictionaries for the map app

state_list = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 
'Colorado', 'Connecticut', 'Delaware', 'Florida', 
'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 
'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 
'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 
'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 
'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 
'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 
'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']

codeToStates = {
        '02': 'Alaska',
        '01': 'Alabama',
        '04': 'Arkansas',
        '05': 'Arizona',
        '06': 'California',
        '08': 'Colorado',
        '09': 'Connecticut',
        '10': 'Delaware',
        '12': 'Florida',
        '13': 'Georgia',
        '15': 'Hawaii',
        '19': 'Iowa',
        '16': 'Idaho',
        '17': 'Illinois',
        '18': 'Indiana',
        '20': 'Kansas',
        '21': 'Kentucky',
        '22': 'Louisiana',
        '25': 'Massachusetts',
        '24': 'Maryland',
        '23': 'Maine',
        '26': 'Michigan',
        '27': 'Minnesota',
        '29': 'Missouri',
        '28': 'Mississippi',
        '30': 'Montana',
        '37': 'North Carolina',
        '38': 'North Dakota',
        '31': 'Nebraska',
        '33': 'New Hampshire',
        '34': 'New Jersey',
        '35': 'New Mexico',
        '32': 'Nevada',
        '36': 'New York',
        '39': 'Ohio',
        '40': 'Oklahoma',
        '41': 'Oregon',
        '42': 'Pennsylvania',
        '44': 'Rhode Island',
        '45': 'South Carolina',
        '46': 'South Dakota',
        '47': 'Tennessee',
        '48': 'Texas',
        '49': 'Utah',
        '51': 'Virginia',
        '50': 'Vermont',
        '53': 'Washington',
        '55': 'Wisconsin',
        '54': 'West Virginia',
        '56': 'Wyoming'
}

statesToCode = {
        'Alabama'        :	'01',
        'Alaska'         :      '02',
        'Arizona'        :	'04',
        'Arkansas'       :      '05',
        'California'     :	'06',
        'Colorado'       :	'08',
        'Connecticut'    :      '09',
        'Delaware'       :      '10',
        'Florida'	 :      '12',
        'Georgia'	 :      '13',
        'Hawaii'	 :      '15',
        'Idaho'	         :      '16',
        'Illinois'	 :      '17',
        'Indiana'	 :      '18',
        'Iowa'	         :      '19',
        'Kansas'	 :      '20',
        'Kentucky'	 :      '21',
        'Louisiana'	 :      '22',
        'Maine'	         :      '23',
        'Maryland'	 :      '24',
        'Massachusetts'	 :      '25',
        'Michigan'	 :      '26',
        'Minnesota'	 :      '27',
        'Mississippi'	 :      '28',
        'Missouri'	 :      '29',
        'Montana'	 :      '30',
        'Nebraska'	 :      '31',
        'Nevada'	 :      '32',
        'New Hampshire'	 :      '33',
        'New Jersey'	 :      '34',
        'New Mexico'	 :      '35',
        'New York'	 :      '36',
        'North Carolina' :	'37',
        'North Dakota'   :	'38',
        'Ohio'	         :      '39',
        'Oklahoma'	 :      '40',
        'Oregon'	 :      '41',
        'Pennsylvania'	 :      '42',
        'Rhode Island'	 :      '44',
        'South Carolina' :	'45',
        'South Dakota'	 :      '46',
        'Tennessee'	 :      '47',
        'Texas'	         :      '48',
        'Utah'	         :      '49',
        'Vermont'	 :      '50',
        'Virginia'	 :      '51',
        'Washington'	 :      '53',
        'West Virginia'	 :      '54',
        'Wisconsin'	 :      '55',
        'Wyoming'	 :      '56'
}