# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170607_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_code',
            field=models.IntegerField(null=True),
        ),
    ]
