# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_state_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='employment',
            field=models.IntegerField(null=True),
        ),
    ]
